Traceback (most recent call last):
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukem/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
latitude = [78.5142,79.2833,79.9840]
longitude = [30.4231,30.3591,30.4994, 30.4200]

xrds = xr.Dataset(
    coords = {
        'depth': depth,
        'time': time
    },
    data_vars = {
        'sea_water_temperature': (['time','depth'],temperature_2d),
        'latitude': ('time', latitude),
        'longitude': ('time', longitude)
    }
)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[13], line 4[0m
[1;32m      1[0m latitude [38;5;241m=[39m [[38;5;241m78.5142[39m,[38;5;241m79.2833[39m,[38;5;241m79.9840[39m]
[1;32m      2[0m longitude [38;5;241m=[39m [[38;5;241m30.4231[39m,[38;5;241m30.3591[39m,[38;5;241m30.4994[39m, [38;5;241m30.4200[39m]
[0;32m----> 4[0m xrds [38;5;241m=[39m xr[38;5;241m.[39mDataset(
[1;32m      5[0m     coords [38;5;241m=[39m {
[1;32m      6[0m         [38;5;124m'[39m[38;5;124mdepth[39m[38;5;124m'[39m: depth,
[1;32m      7[0m         [38;5;124m'[39m[38;5;124mtime[39m[38;5;124m'[39m: time
[1;32m      8[0m     },
[1;32m      9[0m     data_vars [38;5;241m=[39m {
[1;32m     10[0m         [38;5;124m'[39m[38;5;124msea_water_temperature[39m[38;5;124m'[39m: ([[38;5;124m'[39m[38;5;124mtime[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mdepth[39m[38;5;124m'[39m],temperature_2d),
[1;32m     11[0m         [38;5;124m'[39m[38;5;124mlatitude[39m[38;5;124m'[39m: ([38;5;124m'[39m[38;5;124mtime[39m[38;5;124m'[39m, latitude),
[1;32m     12[0m         [38;5;124m'[39m[38;5;124mlongitude[39m[38;5;124m'[39m: ([38;5;124m'[39m[38;5;124mtime[39m[38;5;124m'[39m, longitude)
[1;32m     13[0m     }
[1;32m     14[0m )

File [0;32m~/anaconda3/lib/python3.11/site-packages/xarray/core/dataset.py:652[0m, in [0;36mDataset.__init__[0;34m(self, data_vars, coords, attrs)[0m
[1;32m    649[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(coords, Dataset):
[1;32m    650[0m     coords [38;5;241m=[39m coords[38;5;241m.[39m_variables
[0;32m--> 652[0m variables, coord_names, dims, indexes, _ [38;5;241m=[39m merge_data_and_coords(
[1;32m    653[0m     data_vars, coords, compat[38;5;241m=[39m[38;5;124m"[39m[38;5;124mbroadcast_equals[39m[38;5;124m"[39m
[1;32m    654[0m )
[1;32m    656[0m [38;5;28mself[39m[38;5;241m.[39m_attrs [38;5;241m=[39m [38;5;28mdict[39m(attrs) [38;5;28;01mif[39;00m attrs [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;28;01melse[39;00m [38;5;28;01mNone[39;00m
[1;32m    657[0m [38;5;28mself[39m[38;5;241m.[39m_close [38;5;241m=[39m [38;5;28;01mNone[39;00m

File [0;32m~/anaconda3/lib/python3.11/site-packages/xarray/core/merge.py:569[0m, in [0;36mmerge_data_and_coords[0;34m(data_vars, coords, compat, join)[0m
[1;32m    567[0m objects [38;5;241m=[39m [data_vars, coords]
[1;32m    568[0m explicit_coords [38;5;241m=[39m coords[38;5;241m.[39mkeys()
[0;32m--> 569[0m [38;5;28;01mreturn[39;00m merge_core(
[1;32m    570[0m     objects,
[1;32m    571[0m     compat,
[1;32m    572[0m     join,
[1;32m    573[0m     explicit_coords[38;5;241m=[39mexplicit_coords,
[1;32m    574[0m     indexes[38;5;241m=[39mIndexes(indexes, coords),
[1;32m    575[0m )

File [0;32m~/anaconda3/lib/python3.11/site-packages/xarray/core/merge.py:761[0m, in [0;36mmerge_core[0;34m(objects, compat, join, combine_attrs, priority_arg, explicit_coords, indexes, fill_value)[0m
[1;32m    756[0m prioritized [38;5;241m=[39m _get_priority_vars_and_indexes(aligned, priority_arg, compat[38;5;241m=[39mcompat)
[1;32m    757[0m variables, out_indexes [38;5;241m=[39m merge_collected(
[1;32m    758[0m     collected, prioritized, compat[38;5;241m=[39mcompat, combine_attrs[38;5;241m=[39mcombine_attrs
[1;32m    759[0m )
[0;32m--> 761[0m dims [38;5;241m=[39m calculate_dimensions(variables)
[1;32m    763[0m coord_names, noncoord_names [38;5;241m=[39m determine_coords(coerced)
[1;32m    764[0m [38;5;28;01mif[39;00m explicit_coords [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m~/anaconda3/lib/python3.11/site-packages/xarray/core/variable.py:3282[0m, in [0;36mcalculate_dimensions[0;34m(variables)[0m
[1;32m   3280[0m             last_used[dim] [38;5;241m=[39m k
[1;32m   3281[0m         [38;5;28;01melif[39;00m dims[dim] [38;5;241m!=[39m size:
[0;32m-> 3282[0m             [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m   3283[0m                 [38;5;124mf[39m[38;5;124m"[39m[38;5;124mconflicting sizes for dimension [39m[38;5;132;01m{[39;00mdim[38;5;132;01m!r}[39;00m[38;5;124m: [39m[38;5;124m"[39m
[1;32m   3284[0m                 [38;5;124mf[39m[38;5;124m"[39m[38;5;124mlength [39m[38;5;132;01m{[39;00msize[38;5;132;01m}[39;00m[38;5;124m on [39m[38;5;132;01m{[39;00mk[38;5;132;01m!r}[39;00m[38;5;124m and length [39m[38;5;132;01m{[39;00mdims[dim][38;5;132;01m}[39;00m[38;5;124m on [39m[38;5;132;01m{[39;00mlast_used[38;5;132;01m!r}[39;00m[38;5;124m"[39m
[1;32m   3285[0m             )
[1;32m   3286[0m [38;5;28;01mreturn[39;00m dims

[0;31mValueError[0m: conflicting sizes for dimension 'time': length 3 on 'latitude' and length 4 on {'time': 'sea_water_temperature', 'depth': 'sea_water_temperature'}
ValueError: conflicting sizes for dimension 'time': length 3 on 'latitude' and length 4 on {'time': 'sea_water_temperature', 'depth': 'sea_water_temperature'}

